const HIDE_MODAL = {
  type: 'HIDE_MODAL',
}

const SHOW_MODAL_HIDE_MOB_MENU = {
  type: 'SHOW_MODAL_HIDE_MOB_MENU',
}

const SHOW_MOB_MENU = {
  type: 'SHOW_MOB_MENU',
}

const HIDE_MOB_MENU = {
  type: 'HIDE_MOB_MENU',
}

export { HIDE_MODAL, SHOW_MODAL_HIDE_MOB_MENU, SHOW_MOB_MENU, HIDE_MOB_MENU }
